---
title: "Module_12"
author: "Erin Anderson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(curl)
library(ggplot2)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/zombies.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
```
```{r 2, include=TRUE}
w <- d$weight
h <- d$height
n <- length(w)  # or length(h)
cov_wh <- sum((w - mean(w)) * (h - mean(h)))/(n - 1)
cov_wh
cov(w, h)
```

```{r 4, include=TRUE}
sd_w <- sd(w)
sd_h <- sd(h)
cor_wh <- cov_wh/(sd_w * sd_h)
cor_wh
cor(w, h)
cor(w, h, method = "pearson")
cor(w, h, method = "spearman")
cor(w, h, method = "kendall")
```

```{r 5, include=TRUE}
y <- h - mean(h)
x <- w - mean(w)
z <- data.frame(cbind(x, y))
g <- ggplot(data = z, aes(x = x, y = y)) + geom_point()
g
slope.test <- function(beta1) {
    g <- ggplot(data = z, aes(x = x, y = y))
    g <- g + geom_point()
    g <- g + geom_abline(intercept = 0, slope = beta1, size = 1, colour = "blue",
        alpha = 1/2)
    ols <- sum((y - beta1 * x)^2)
    g <- g + ggtitle(paste("Slope = ", beta1, "\nSum of Squared Deviations = ",
        round(ols, 3)))
    g
}
```


```{r 6, include=TRUE}
y <- h - mean(h)
x <- w - mean(w)
z <- data.frame(cbind(x, y))
g <- ggplot(data = z, aes(x = x, y = y)) + geom_point()
g
```

```{r 7, include=TRUE}
library(ggplot2)
manipulate(plot(1:5, cex = size), size = slider(0.5, 10, step = 0.5))  #priming the interface
manipulate(slope.test(beta1), beta1 = slider(-1, 1, initial = 0, step = 0.005))  #here we go!
slope.test <- function(beta1) {
    g <- ggplot(data = z, aes(x = x, y = y))
    g <- g + geom_point()
    g <- g + geom_abline(intercept = 0, slope = beta1, size = 1, colour = "blue",
        alpha = 1/2)
    ols <- sum((y - beta1 * x)^2)
    g <- g + ggtitle(paste("Slope = ", beta1, "\nSum of Squared Deviations = ",
        round(ols, 3)))
    g
}
```

```{r 8, include=TRUE}
beta1 <- cor(w, h) * (sd(h)/sd(w))
beta1
beta1 <- cov(w, h)/var(w)
beta1
beta1 <- sum((h - mean(h)) * (w - mean(w)))/sum((w - mean(w))^2)
beta1
beta0 <- mean(h) - beta1 * mean(w)
beta0
```

```{r 9, include=TRUE}
m <- lm(height ~ weight, data = d)
#left is response, right is predictor
m
#lm runs regressions
names(m)
m$coefficients
head(m$model)
```
```{r 10, include=TRUE}
g <- ggplot(data = d, aes(x = weight, y = height))
g <- g + geom_point()
g <- g + geom_smooth(method = "lm", formula = y ~ x)
g
```
```{r 11, include=TRUE}
library(lmodel2)  # load the lmodel2 package
# Run the regression
# model 2 regressions accept that both predictors and responses have error
#this package allows us to run models one and two regressions
mII <- lmodel2(height ~ weight, data = d, range.y = "relative", range.x = "relative",
    nperm = 1000)
mII
```

```{r 12, include = TRUE}
plot(mII, "OLS")
```
```{r 13, include = TRUE}
plot(mII, "RMA")
```

```{r 14, include = TRUE}
plot(mII, "SMA")
```

```{r 15, include = TRUE}
plot(mII, "MA")
```

```{r 16, include = TRUE}
mI <- lm(height ~ weight, data = d)
summary(mI)
par(mfrow = c(1, 2))
plot(mII, main = "lmodel2() OLS")
plot(data = d, height ~ weight, main = "lm()")
abline(mI)
```
